language: node_js
node_js:
  - "13"
  - "12"
  - "10"
  - "9"
  - "8"
  - "iojs"
  - "12"
  - "10"
  - "8"
before_install:
  # Old npm certs are untrusted https://github.com/npm/npm/issues/20191
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.8" ]; then export NPM_CONFIG_STRICT_SSL=false; fi'
  - 'nvm install-latest-npm'
